{
  description = "Feature 13: Makefile Input - Integrates input generated by a Makefile target.";

  inputs = {
    nixpkgs.url = "github:meta-introspector/nixpkgs?ref=feature/CRQ-016-nixify";
    flake-utils.url = "github:meta-introspector/flake-utils?ref=feature/CRQ-016-nixify";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit lib;

        # A function that takes an input string (presumably from a Makefile)
        # and creates a derivation with that input.
        processMakefileInput = { inputString }:
          pkgs.stdenv.mkDerivation {
            pname = "makefile-input-processor";
            version = "1.0";

            src = pkgs.writeText "input.txt" inputString;

            buildPhase = ''
              mkdir -p $out
              cp $src $out/processed-input.txt
              echo "Input from Makefile: $(cat $src)" >> $out/processed-input.txt
            '';

            installPhase = ''
              echo "Processed Makefile input available in $out/processed-input.txt"
            '';
          };

      in
      {
        lib = {
          inherit processMakefileInput;
        };

        packages.default = pkgs.writeText "makefile-input-feature" "This flake integrates Makefile generated input.";
      }
    );
}
