{
  description = "A Nix flake for generating a domain-specific knowledge graph for LLM context.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      systems = [ "aarch64-linux" "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgs = forAllSystems (system: import nixpkgs {
        inherit system;
      });

      # Path to the generated knowledge data (JSON Lines format)
      # This file must be generated by running:
      # scripts/discover_project_urls.sh | scripts/extract_and_optimize_knowledge.py > knowledge_data.jsonl
      # knowledgeDataPath = ./knowledge_data.jsonl;

      # Read and parse the JSON Lines data
      # Note: For very large datasets, this might be inefficient as it reads the whole file.
      # A more robust solution might involve a derivation that processes the JSON Lines file incrementally.
      # knowledgeItems = builtins.fromJSON (builtins.readFile knowledgeDataPath);
      knowledgeItems = [];

      # Group knowledge items by TLD
      # groupedByTld = nixpkgs.lib.groupBy (item: item.tld) knowledgeItems;
      groupedByTld = {};

      # Function to create a derivation for a single knowledge item
      mkKnowledgeItemDerivation = system: item:
        pkgs.${system}.stdenv.mkDerivation {
          pname = "knowledge-${nixpkgs.lib.strings.sanitizeDerivationName item.tld}-${nixpkgs.lib.strings.sanitizeDerivationName (builtins.substring 0 10 item.url)}";
          version = "0.1";

          # The content itself is the source
          src = pkgs.${system}.writeText "content.txt" item.content;

          # Install phase just copies the content to the output
          installPhase = ''
            mkdir -p $out
            cp $src $out/content.txt
          '';

          # Custom attributes for metadata
          url = item.url;
          tld = item.tld;
          contentLength = item.length;
          # Add other metadata as needed (e.g., hash of content, last fetched date)
        };

      # Generate packages for each TLD, aggregating their individual knowledge items
      tldPackages = forAllSystems (system:
        nixpkgs.lib.mapAttrs
          (tld: items:
            pkgs.${system}.stdenv.mkDerivation {
              pname = "knowledge-tld-${nixpkgs.lib.strings.sanitizeDerivationName tld}";
              version = "0.1";

              # This derivation will contain a directory of all items for this TLD
              # We'll create a simple directory structure with symlinks to individual item NARs
              buildInputs = [ pkgs.${system}.coreutils ]; # For cp and ln

              installPhase = ''
                mkdir -p $out/${tld}
                ${nixpkgs.lib.concatStringsSep "\n" (nixpkgs.lib.map (item: 
                  let
                    itemDerivation = mkKnowledgeItemDerivation system item;
                    # Sanitize URL for a valid filename, potentially hash for uniqueness
                    sanitizedUrlFileName = nixpkgs.lib.strings.sanitizeDerivationName (builtins.substring 0 50 item.url);
                  in
                  "ln -s ${itemDerivation}/content.txt $out/${tld}/${sanitizedUrlFileName}.txt"
                ) items)}
              '';

              # Custom attributes for the TLD package
              domain = tld;
              itemCount = builtins.length items;
              # Add other TLD-level metadata (e.g., total content length, list of all URLs)
            }
          )
          groupedByTld
      );

    in
    {
      packages = forAllSystems (system: tldPackages.${system});

      devShells = forAllSystems (system: {
        default = pkgs.${system}.mkShell {
          buildInputs = with pkgs.${system}; [
            bash
            nixpkgs-fmt
          ];
        };
      });
    }; # Closing brace for outputs
} # Closing brace for the entire flake