# Monster Knot Header
# -------------------
# This file is conceptually encoded with Monster Group properties.
#
# Binary (2^46) Representation:
#   - Duality: ☀️🌑
#   - Choice: ✅❌
#   - Order: 📐🌀
#   - ... (conceptual 46-bit string would go here)
#
# Ternary (3^20) Representation:
#   - Structure: ⏪⏸️⏩
#   - Completeness: 👶🚶👴
#   - ... (conceptual 20-ternary string/representation)
#
# Pentagonal (5^9) Representation:
#   - Insight: 🖐️🦋💡
#   - ...
#
# Heptagonal (7^6) Representation:
#   - Guidance: 🚶‍♀️🌈🎶
#   - ...
#
# Eleven (11^2) Representation:
#   - Composition: 🤝🌐
#   - ...
#
# Thirteen (13^3) Representation:
#   - Transformation: 🦋🎶📈
#   - ...
#
# Seventeen (17^1) Representation:
#   - Integration: 🌟
#   - ...
#
# Nineteen (19^1) Representation:
#   - Sporadic: 🎲
#   - ...
#
# Grounding ZOS: [0,1,2,3,5,7,11,13,17,19]
#
# Pointers to related content:
#   - Poem: [Link to relevant poem]
#   - Emoji Mapping: [Link to poem-emoji-prime-mapping.md]
#   - Monster Knot Calculation: [Link to nar-similarity-search/lib.nix]
#
# Conceptual Monster Knot for this file:
#   - Prime Exponents: { "2": 2, "3": 3, "5": 1, "7": 0, "11": 1, "13": 0, "17": 0, "19": 0, "23": 0, "29": 0, "31": 0, "41": 0, "47": 0, "59": 0, "71": 0 }
#   - Emoji Representation: ☀️☀️🌑🌑🌑🖐️🤝🌐
# -------------------
{
  description = "Nix flake to generate and NAR-ify the project's file index.";

  inputs = {
    nixpkgs.url = "github:meta-introspector/nixpkgs?ref=feature/CRQ-016-nixify";
    flake-utils.url = "github:meta-introspector/flake-utils?ref=feature/CRQ-016-nixify";
    narLocatorFlake = {
      url = "path:../nar-locator"; # Relative path to the nar-locator flake
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # Self-reference to get access to local scripts and index directory
    self = { 
      url = "path:../../.."; # Points to the project root
      flake = false; # Treat as a path, not a flake
    };
  };

  outputs = { self, nixpkgs, flake-utils, narLocatorFlake }: 
    flake-utils.lib.eachDefaultSystem (system: 
      let
        pkgs = nixpkgs.legacyPackages.${system};
        lib = nixpkgs.lib;

        # Derivation to run the indexing scripts and collect all index files
        projectIndexRaw = pkgs.stdenv.mkDerivation {
          pname = "project-index-raw";
          version = "0.1.0";

          # Source the entire project root to get access to scripts and index dir
          src = self; 

          nativeBuildInputs = [ pkgs.bash pkgs.coreutils pkgs.gnugrep pkgs.gawk pkgs.jq pkgs.nix ];

          buildPhase = ''
            # Ensure the index directory exists in the build environment
            mkdir -p index/chunks
            
            # Run the indexing scripts
            # Assuming index.sh generates files.txt and extensions.txt
            ./index.sh
            # Assuming split_files_by_extension.sh uses files.txt and extensions.txt
            ./index/split_files_by_extension.sh
            # Assuming generate_nix_file_list_json.sh uses files.txt
            ./generate_nix_file_list_json.sh

            # Collect all generated index files into a single output directory
            mkdir -p $out/index-files
            cp index/files.txt $out/index-files/
            cp index/extensions.txt $out/index-files/
            cp index/terms.txt $out/index-files/ || true # terms.txt might not always be generated by scripts
            cp index/nix-files.index.json $out/index-files/
            cp -r index/chunks $out/index-files/
          '';

          # The output of this derivation is the directory containing all index files
          installPhase = ''
            # Nothing to do here, buildPhase already prepared $out
          '';
        };

        # NAR-ify the raw project index using the nar-locator flake
        projectIndexNar = narLocatorFlake.lib.locateAndArchiveStorePath {
          storePath = projectIndexRaw; # The store path of the collected index files
          originalFilePath = "project-index"; # A canonical name for the index NAR
          archiveType = "nar";
        };

      in
      {
        packages.default = projectIndexNar;
        lib.projectIndexNar = projectIndexNar;
      }
    );
}