{ pkgs, lib, builtins, llmGeneratorFlake }:
{
  name = "auto-document-flake";
  description = "Automatically documents a flake.nix file using an LLM, checking for existing documentation first.";
  script = pkgs.writeScript "auto-document-flake-script" ''
    flake_path="$1"
    if [ -z "$flake_path" ]; then
      echo "Usage: run-task <path_to_flake.nix>"
      exit 1
    fi

    echo "Checking $flake_path for existing docs.md target..."
    # A simplified check for the presence of 'docs.md =' in the flake.nix
    if grep -q "docs.md =" "$flake_path"; then
      echo "docs.md target already exists in $flake_path. Skipping."
    else
      echo "docs.md target not found. Requesting LLM to generate documentation..."

      # In a real scenario, this would invoke the llmGeneratorFlake
      # to get the documentation content. For now, we'll use a placeholder.
      # The actual LLM call would be complex, involving Nix evaluation
      # of the llmGeneratorFlake and parsing its output.
      # For demonstration, we'll simulate LLM output.
      
      # Simulate LLM call to get documentation content
      # This would typically involve a nix build/run command against llmGeneratorFlake
      # For example: nix run $llmGeneratorFlake.packages.${pkgs.system}.llmDocGenerator -- "$flake_path"
      
      # Placeholder for LLM-generated content
      generated_docs="# Documentation for $(basename "$flake_path")\n\nThis documentation was automatically generated by an LLM.\n\n## Purpose\n(LLM-generated purpose here)\n\n## Inputs\n(LLM-generated inputs here)\n\n## Outputs\n(LLM-generated outputs here)"

      echo "LLM generated documentation content."

      # Append the docs.md target to the flake.nix
      # This is a simplified append. A robust solution would use 'replace'
      # to find the correct insertion point and handle indentation.
      echo "" >> "$flake_path"
      echo "      docs.md = pkgs.writeText \"$(basename "$flake_path" .nix)-docs.md\" ''" >> "$flake_path"
      echo "$generated_docs" >> "$flake_path"
      echo "      '';" >> "$flake_path"
      echo "Documentation added to $flake_path."
    fi
  '';
}
