{ lib, pkgs }:
{
  name = "task-execution-spec";
  description = "Specification for a task that executes an LLM task plan, making actual LLM API calls (impurely) and producing raw results.";
  taskType = "execution";
  inputs = {
    executionPlan = "A derivation containing the execution plan generated by the /plan task.";
    llmImplementationPlugin = "A derivation containing the concrete LLM model and credential bindings.";
  };
  outputs = {
    rawResults = "A derivation containing the raw, unverified results from the LLM API calls.";
  };
}
