{
  description = "Flake for AI Life Mycology - Monster Group Prime Lattice";

  inputs = {
    self.url = "github:meta-introspector/time-2025?ref=feature/aimyc-003-cultivation";
    nixpkgs.url = "github:meta-introspector/nixpkgs?ref=feature/CRQ-016-nixify";
    bagOfWordsGenerator.url = "github:meta-introspector/time-2025?ref=feature/aimyc-003-cultivation&dir=flakes/bag-of-words-generator";
  };

  outputs = { self, nixpkgs, bagOfWordsGenerator, ... }@inputs:
    let
      system = "aarch64-linux";
      pkgs = import nixpkgs { inherit system; };
      inherit (pkgs) lib;

      flakeUtils = (import ./lib/flake-utils.nix) { inherit pkgs lib; };

      llmPipelineResults = (import ./lib/llm-pipeline.nix) {
        inherit pkgs lib self bagOfWordsGenerator;
        flakeFile = ./flake.nix;
      };

      finalOutputs = (import ./lib/outputs.nix) {
        inherit pkgs lib flakeUtils llmPipelineResults;
      };
    in
    {
      packages.${system} = {
        default = flakeUtils.monsterGroupPrimeLattice.monsterGroupJson;
        llmResultsInitial = llmPipelineResults.llmOrchestratorInitial;
        llmResultsFixme = llmPipelineResults.llmOrchestratorFixme;
      };

      lib.monsterGroupData = flakeUtils.monsterGroupPrimeLattice.monsterGroupData;

      lib.previousVersionChecksum = llmPipelineResults.llmCallVectorDescription.calls .0.checksum; # Assuming first call's checksum

      lib.llmCallVectorDescription = llmPipelineResults.llmCallVectorDescription;

      lib.debugDump = {
        llmCallVector = llmPipelineResults.llmCallVectorDescription;
        keyObject = llmPipelineResults.myKeyObject;
        modelRouter = llmPipelineResults.myModelRouter;
        llmOrchestratorDerivation = llmPipelineResults.llmOrchestrator;
        bagOfWordsReport = llmPipelineResults.bagOfWordsReportContent;
      };

      docs.md = pkgs.writeText "mycology-flake-docs.md" ''
        # AI Life Mycology - Monster Group Prime Lattice Flake

        ## Description

        This flake is central to the AI Life Mycology project, focusing on the "Monster Group Prime Lattice" concept. It orchestrates an LLM pipeline to generate tasks based on source code analysis.

        ## Inputs

        -   `self`: Reference to this flake itself.
        -   `nixpkgs`: Standard Nixpkgs.
        -   `bagOfWordsGenerator`: A flake that provides functionality to generate bag-of-words reports from `flake.nix` files.

        ## Outputs

        ### `packages.${system}.llmResultsInitial`

        A derivation representing the initial results from the LLM orchestration pipeline. This likely involves initial LLM calls based on the source analysis.

        ### `packages.${system}.llmResultsFixme`

        A derivation representing the "fixme" tasks generated by the LLM pipeline. These are the identified issues or tasks that are intended to be fed into the workpool for miners.

        ### `lib.monsterGroupData`

        Provides data related to the Monster Group Prime Lattice.

        ### `lib.llmCallVectorDescription`

        A description of the LLM calls made during the pipeline execution.

        ### `lib.debugDump`

        Contains various debug information, including LLM call vectors, key objects, model router configuration, LLM orchestrator derivation, and bag-of-words report content.
      '';
    };
}	
    
