{ lib, ... }:

{
  generateCode = args: {
    derivationCode = "# Generated by Real Gemini for: ${args.prompt}\n{ pkgs }: pkgs.stdenv.mkDerivation { name = \"real-derivation\"; src = ./.; buildPhase = \"echo 'Real build for ${args.prompt}'\"; }\n";
  };
}
