#!/usr/bin/env bash
set -euo pipefail

TEMPLATE_FILE="/data/data/com.termux.nix/files/home/pick-up-nix2/source/github/meta-introspector/streamofrandom/2025/scripts/Makefile.template"
MAKEFILES_TO_UPDATE=(
./09/22/flake-reconstruction-lattice/Makefile
./09/22/nix-llm-task/Makefile
./09/22/flake-templates/llm-task-template/Makefile
./09/22/Makefile
./09/22/nix-llm-context/lib/Makefile
./09/22/nix-llm-context/Makefile
./09/23/nix_concepts_and_facts/concepts/Makefile
./09/23/nix_concepts_and_facts/lib/Makefile
./09/23/nix_concepts_and_facts/Makefile
./09/23/Makefile
./09/25/log_analyzer/flakes/log-analysis-pipeline/Makefile
./09/25/log_analyzer/flakes/log-analysis-pipeline/lib/Makefile
./09/25/log_analyzer/flakes/log-analysis-pipeline/packages/Makefile
./09/25/log_analyzer/flakes/log-analysis-pipeline/test-cases/Makefile
./09/25/log_analyzer/Makefile
./09/25/rungemini/Makefile
./09/25/primes/Makefile
./09/25/Makefile
./09/26/synapse-system/Makefile
./09/26/synapse-system/nix/flakes/4QZero/Makefile
./09/26/synapse-system/nix/flakes/architect/Makefile
./09/26/synapse-system/nix/flakes/base-agent/Makefile
./09/26/synapse-system/nix/flakes/clarity-judge/Makefile
./09/26/synapse-system/nix/flakes/code-hound/Makefile
./09/26/synapse-system/nix/flakes/devops-engineer/Makefile
./09/26/synapse-system/nix/flakes/docs-writer/Makefile
./09/26/synapse-system/nix/flakes/file-creator/Makefile
./09/26/synapse-system/nix/flakes/git-workflow/Makefile
./09/26/synapse-system/nix/flakes/golang-specialist/Makefile
./09/26/synapse-system/nix/flakes/python-specialist/Makefile
./09/26/synapse-system/nix/flakes/rust-specialist/Makefile
./09/26/synapse-system/nix/flakes/security-specialist/Makefile
./09/26/synapse-system/nix/flakes/synapse-project-manager/Makefile
./09/26/synapse-system/nix/flakes/test-runner/Makefile
./09/26/synapse-system/nix/flakes/tool-runner/Makefile
./09/26/synapse-system/nix/flakes/typescript-specialist/Makefile
./09/26/synapse-system/nix/flakes/ux-designer/Makefile
./09/26/synapse-system/nix/modules/Makefile
./09/26/synapse-system/nix/Makefile
./09/26/synapse-system/tests/python/step1/nix/flakes/agent/Makefile
./09/26/synapse-system/tests/python/step1/nix/modules/Makefile
./09/26/synapse-system/tests/python/step1/nix/Makefile
./09/26/synapse-system/tests/python/step1/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/debug/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/lib/extractor/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/mach_nix/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/mach_nix/nix/from-nixpkgs/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/mach_nix/nix/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/pypi-crawlers/nix/crawler/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/pypi-crawlers/nix/database/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/pypi-crawlers/nix/power-deps-crawler/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/pypi-crawlers/nix/power-wheels-crawler/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/pypi-crawlers/nix/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/pypi-crawlers/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/tests/Makefile
./09/26/synapse-system/vendor/nix/mach-nix/Makefile
./09/26/synapse-system/vendor/nix/pip2nix/examples/shell/Makefile
./09/26/synapse-system/vendor/nix/pip2nix/nix/Makefile
./09/26/synapse-system/vendor/nix/pip2nix/Makefile
./09/26/synapse-system/vendor/nix/pynixify/nix/packages/pynixify/Makefile
./09/26/synapse-system/vendor/nix/pynixify/nix/packages/types-aiofiles/Makefile
./09/26/synapse-system/vendor/nix/pynixify/nix/Makefile
./09/26/synapse-system/vendor/nix/pynixify/pynixify/data/Makefile
./09/26/synapse-system/vendor/nix/pynixify/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/aliases/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/dev-flake/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/basics/derivation/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/basics/htop-with-flags/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/basics/mkDerivation/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/haskell-local-development-cabal/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/nodejs-local-development-nextjs/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/nodejs-local-development-no-lock-file/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/nodejs-packaging-devshell-only/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/nodejs-packaging/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/php-packaging/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-local-development-machine-learning/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-local-development-multiple-packages/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-local-development-pdm-pytorch-from-nixpkgs/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-local-development-pdm/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-local-development/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-packaging-ansible/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-packaging-apache-airflow/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-packaging-odoo/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/python-packaging-pillow/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/rust-local-development-workspace/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/rust-packaging-buildRustPackage/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/rust-packaging/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/packages/languages/spago-local-development/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/repo-with-packages-flake/packages/hello/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/repo-with-packages-flake/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/repo-with-packages/packages/hello/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/examples/repo-with-packages/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/archive/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/crates-io/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/git/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/github/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/gitlab/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/http/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/npm/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/path/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/pypi-sdist/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/pypi-wheel/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/fetchers/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/internal/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/types/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/lib/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/misc/benchmarks/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/misc/drafts/repo-flake-groups/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-groups/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-haskell-cabal/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-nodejs-builder-v3/modules/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-nodejs-builder-v3/tests/packages/nodejs-nextjs/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-nodejs-builder-v3/tests/packages/nodejs-packaging-package-lock-v1/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-nodejs-builder-v3/tests/packages/nodejs-packaging-package-lock/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-nodejs-builder-v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-python-pyproject/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/WIP-spago/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/_template/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/buildPythonPackage-mixin/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/buildPythonPackage-mixin/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/buildPythonPackage/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/buildPythonPackage/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/buildRustPackage/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/builtins-derivation/derivation-common/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/builtins-derivation/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/deps/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/docs/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/env/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/eval-cache/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/flags/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/lock/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/paths/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/public/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/tests/packages/nixpkgs/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/ui/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/core/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/mkDerivation-mixin/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/mkDerivation-mixin/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/mkDerivation/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/mkDerivation/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/multi-derivation-package/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nixpkgs-overrides/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-devshell-v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-devshell/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-devshell/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-granular-v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-granular/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-node-modules-v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-node-modules/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-node-modules/tests/packages/nodejs-packaging-node-modules-only/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-node-modules/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-package-json-v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-package-json/tests/packages/basic/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-package-json/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-package-lock-v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/nodejs-package-lock/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/overrides/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/package-func/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/php-composer-lock/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/php-granular/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/pip/pip-hotfixes/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/pip/tests/packages/can-build-setuptools/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/pip/tests/packages/can-handle-setuptools-runtime-dep/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/pip/tests/packages/lock-script-works/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/pip/tests/packages/python-nodejs/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/pip/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/python-editables/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/python-pdm/tests/packages/jupyter-lab/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/python-pdm/tests/packages/python-local-development/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/python-pdm/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/rust-cargo-lock/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/rust-cargo-vendor/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/dream2nix/rust-crane/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/flake-parts/pythonEnv/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/flake-parts/reference-website/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/modules/flake-parts/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/_template/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/certifi/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cublas-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cuda-cupti-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cuda-nvrtc-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cuda-runtime-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cudnn-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cufft-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-curand-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cusolver-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-cusparse-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-nccl-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/nvidia-nvjitlink-cu12/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/opencv-python/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/pillow/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/psycopg2/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/reuse/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/torch/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/python/triton/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/overrides/rust/jack-sys/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/pkgs/fetchPipMetadata/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/pkgs/writers/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/scripts/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_findCycles/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_graph_utils/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_groups/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_groups_multi_derivation_package/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_nodejs_lock_v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_nodejs_lockutils/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_nodejs_node_builder_v3/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_paths/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_pip_pyproject/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_python-pdm-lib/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/test_python-pdm/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/tests/nix-unit/Makefile
./09/26/synapse-system/vendor/nix/dream2nix/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/dev/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/doc/src/overriding/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/doc/src/patterns/cross/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/doc/src/patterns/development-scripts/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/doc/src/patterns/testing/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/doc/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/lib/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/npins/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/pkgs/uv-bin/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/templates/hello-tkinter/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/templates/hello-world/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/templates/inline-metadata/Makefile
./09/26/synapse-system/vendor/nix/uv2nix/Makefile
./09/26/jobs/test_nix_project/Makefile
./09/26/jobs/vendor/nix-task/examples/nixMathHomework/Makefile
./09/26/jobs/vendor/nix-task/examples/gemini-caller-flake/Makefile
./09/26/jobs/vendor/nix-task/examples/gemini-input-flake/Makefile
./09/26/jobs/vendor/nix-task/nix/lib/Makefile
./09/26/jobs/vendor/nix-task/nix/tasks/Makefile
./09/26/jobs/vendor/nix-task/nix/base-job/Makefile
./09/26/jobs/vendor/nix-task/runner/Makefile
./09/26/jobs/vendor/nix-task/flakes/all-repos/Makefile
./09/26/jobs/vendor/nix-task/Makefile
./09/26/jobs/vendor/nix-eval-jobs/dev/Makefile
./09/26/jobs/vendor/nix-eval-jobs/tests/assets/Makefile
./09/26/jobs/vendor/nix-eval-jobs/Makefile
./09/26/jobs/vendor/Makefile
./09/26/jobs/Makefile
./09/26/Makefile
./09/27/7-concepts/1-build-system/Makefile
./09/27/7-concepts/1-build-system/nix-tests/Makefile
./09/27/7-concepts/1-build-system/nix/packages/lint-staged/Makefile
./09/27/7-concepts/2-gemini-integration/Makefile
./09/27/7-concepts/2-gemini-integration/gemini-integration/Makefile
./09/27/7-concepts/3-response-artifacts/response-007-cli-nar-output/Makefile
./09/27/7-concepts/6-qa-testing/tests/2025-01-27-gemini-hello-world/Makefile
./09/27/7-concepts/6-qa-testing/tests/2025-01-27-minimal-qa-test/Makefile
./09/27/7-concepts/6-qa-testing/tests/2025-01-27-build-time-gemini-capture/Makefile
./09/27/7-concepts/6-qa-testing/tests/consolidated-impure-gemini-telemetry/vial-placeholder/Makefile
./09/27/7-concepts/6-qa-testing/tests/consolidated-impure-gemini-telemetry/Makefile
./09/27/7-concepts/test-secrets-sops/Makefile
./09/27/7-concepts/ai-workflow/Makefile
./09/Makefile
./09/30/monster_experiment/rust_knowledge_extractor/Makefile
./09/flakes/search-results/Makefile
./09/lib/Makefile
./09/theory/Makefile
./09/dummy_project/Makefile
./09/24/nix_custom_attrs_test/Makefile
./10/01/docs/theory/spore_vial_001/Makefile
./10/01/docs/theory/nix_to_owl_ontology_declarations/prefixes/Makefile
./10/01/docs/theory/nix_to_owl_ontology_declarations/Makefile
./10/01/docs/theory/Makefile
./10/02/github-to-foaf/Makefile
./10/02/fetch-github-data/Makefile
./10/03/colosseum-mirror/Makefile
./10/03/lib/Makefile
./10/03/Makefile
./10/04/nix-stdlib/src/formats/Makefile
./10/04/nix-stdlib/src/types/Makefile
./10/04/nix-stdlib/src/Makefile
./10/04/nix-stdlib/Makefile
./10/04/killerjoke/Makefile
./10/04/bootstrap/Makefile
./10/04/gemini-prompt-flake/Makefile
./10/04/lib/Makefile
./10/06/meta-introspector-fetchers/Makefile
./10/06/notebooklm-export/Makefile
./10/06/sops-gemini/flakes/wrap-gemini-secrets/Makefile
./10/06/sops-gemini/Makefile
./10/07/Makefile
./10/08/hackathon/flakes/consolidated-impure-gemini-telemetry-modules/Makefile
./10/Makefile
./docs/memes/10/03/Makefile
./docs/crqs/Makefile
./docs/qa/Makefile
./docs/Makefile
./dummy_project/Makefile
./flakes/foaf/context/Makefile
./flakes/foaf/seed-data/Makefile
./flakes/foaf/aggregator/context/Makefile
./flakes/foaf/aggregator/seed-graph/Makefile
./flakes/foaf/aggregator/full-graph/Makefile
./flakes/foaf/aggregator/lib/Makefile
./flakes/foaf/aggregator/Makefile
./flakes/foaf/github-data/Makefile
./flakes/search-results/Makefile
./flakes/crq-search/parser/Makefile
./flakes/crq-search/reader/Makefile
./flakes/crq-search/filter/Makefile
./flakes/crq-search/sorter-suggester/Makefile
./flakes/crq-search/main/Makefile
./flakes/crq-search-lattice/base/Makefile
./flakes/crq-search-lattice/parser/Makefile
./flakes/crq-search-lattice/layer1/Makefile
./flakes/crq-search-lattice/Makefile
./flakes/crq-document-check/Makefile
./flakes/gemini-feature-lattice/Makefile
./flakes/feature-2-nix-base/Makefile
./flakes/feature-3-home-dir-creds/Makefile
./flakes/feature-5-oauth-creds/Makefile
./flakes/feature-7-telemetry-capture/Makefile
./flakes/feature-11-llm-output-capture/Makefile
./flakes/feature-13-makefile-input/Makefile
./flakes/feature-17-yolo-approval/Makefile
./flakes/feature-19-self-source-input/Makefile
./flakes/composite-2-3-nix-base-home-creds/Makefile
./flakes/composite-2-3-5-nix-base-home-oauth/Makefile
./flakes/composite-2-3-5-7-nix-base-home-oauth-telemetry/Makefile
./flakes/composite-2-3-5-7-11-nix-base-home-oauth-telemetry-llm-output/Makefile
./flakes/composite-2-3-5-7-11-13-nix-base-home-oauth-telemetry-llm-output-makefile-input/Makefile
./flakes/composite-2-3-5-7-11-13-17-nix-base-home-oauth-telemetry-llm-output-makefile-input-yolo/Makefile
./flakes/composite-2-3-5-7-11-13-17-19-nix-base-home-oauth-telemetry-llm-output-makefile-input-yolo-self-source/Makefile
./flakes/with-rust/Makefile
./flakes/mycology-workflow/Makefile
./flakes/data-sources/Makefile
./flakes/article-wrapper/Makefile
./flakes/zos-spore-vial/Makefile
./flakes/nix-to-poem-vial/Makefile
./flakes/read-md-vial/Makefile
./flakes/read-rs-vial/Makefile
./flakes/telemetry-wrapper/Makefile
./github_graphql_modules/Makefile
./github_graphql_parts/Makefile
./lib/generate-project-nix/Makefile
./lib/nix-templates/Makefile
./lib/simple_expr_modules/Makefile
./lib/simple_expr_algebras/Makefile
./lib/utils/Makefile
./lib/simple_expr_traversal_handlers/Makefile
./lib/emoji-encoding/Makefile
./lib/code-generation/Makefile
./lib/llm/Makefile
./lib/monad-context-providers/Makefile
./lib/Makefile
./qa/Makefile
./scripts/test-commit-checker/Makefile
./scripts/Makefile
./solvers/Makefile
./test-bug-repro-nix-2gram-indexer/Makefile
./test-bug-repro-nix-2gram-indexer/tests/Makefile
./test-commit-check/Makefile
./tests/emoji-encoding/Makefile
./theory/Makefile
./theory/leech-lattice-blades.d/Makefile
./theory/mathematical-forms/Makefile
./theory/lib/Makefile
./theory/hackathon-mycology-workflow-puml/Makefile
)

TEMPLATE_CONTENT=$(cat "$TEMPLATE_FILE")

for makefile in "${MAKEFILES_TO_UPDATE[@]}"; do
  echo "Updating $makefile..."
  echo "$TEMPLATE_CONTENT" > "$makefile"
done

echo "All specified Makefiles updated with the template from $TEMPLATE_FILE."
