_:

let
  common = import ../../../lib/common-imports.nix {};
  inherit (common) lib;
  inherit (common) pkgs;
  inherit (common) builtins;

  # Define the structure of the file topology
  # This serves as a schema for the output of our provenance mapping.
  FileTopologySchema = {
    file = null; # Path to the file in the Nix store (string)
    inode = null; # Inode of the file (string, conceptual for Nix store paths)
    ipfs = {
      cid = null; # IPFS Content Identifier (string)
      gatewayUrl = null; # IPFS Gateway URL (string)
    };
    solana = {
      contractAddress = null; # Solana Contract Address (string)
      explorerUrl = null; # Solana Explorer URL (string)
    };
    git = {
      url = null; # URL in Git (string)
      version = null; # Commit hash or tag (string)
      repo = null; # Repository name (string)
      owner = null; # Repository owner (string)
    };
    nar = {
      path = null; # Path to the NAR file in the Nix store (string, conceptual)
      hash = null; # Hash of the NAR file (string, conceptual)
    };
    nix = {
      hash = null; # Nix content hash of the file (string)
      storePath = null; # Full Nix store path of the file (string)
    };
  };

  # A pure Nix function to build the FileTopology for a given file.
  # It takes a file (as a Nix store path) and pre-computed impure data as inputs.
  # The impure data would typically be generated by separate, impure derivations
  # or external tools (e.g., ZKNotary, IPFS daemon, Solana RPC, Git API).
  buildFileTopology = {
    file, # The file (Nix store path) for which to build the topology
    # Impure data that would be generated by external processes and passed in.
    # This keeps the `buildFileTopology` function itself pure.
    impureData ? {
      ipfsCid = null;
      solanaContractAddress = null;
      gitUrl = null;
      gitVersion = null;
      gitOwner = null;
      gitRepo = null;
    },
  }:
  let
    # Pure Nix operations to get file-specific information
    nixHash = pkgs.lib.hashFile "sha256" file;
    nixStorePath = file;

    # Conceptual inode (Nix store paths don't have stable inodes across systems/builds,
    # so this is illustrative of what might be captured by an impure process).
    conceptualInode = "inode-of-${builtins.baseNameOf file}";

    # Conceptual NAR path and hash (would be generated by `nix archive` in an impure step)
    conceptualNarPath = "${nixStorePath}.nar";
    conceptualNarHash = "sha256-NAR_HASH_FOR_${nixHash}";

  in
  FileTopologySchema // {
    inherit file;
    inode = conceptualInode;
    ipfs = {
      cid = impureData.ipfsCid;
      gatewayUrl = if impureData.ipfsCid != null then "https://ipfs.io/ipfs/${impureData.ipfsCid}" else null;
    };
    solana = {
      contractAddress = impureData.solanaContractAddress;
      explorerUrl = if impureData.solanaContractAddress != null then "https://solscan.io/account/${impureData.solanaContractAddress}" else null;
    };
    git = {
      url = impureData.gitUrl;
      version = impureData.gitVersion;
      repo = impureData.gitRepo;
      owner = impureData.gitOwner;
    };
    nar = {
      path = conceptualNarPath;
      hash = conceptualNarHash;
    };
    nix = {
      hash = nixHash;
      storePath = nixStorePath;
    };
  };

in
{
  inherit buildFileTopology;
  inherit FileTopologySchema; # Export the schema definition
}
