{
  description = "Flake to process collectedLocks and provide count and sample. // Forced re-evaluation.";

  inputs = {
    nixpkgs.url = "github:meta-introspector/nixpkgs?ref=feature/CRQ-016-nixify";
    flake-utils.url = "github:meta-introspector/flake-utils?ref=feature/CRQ-016-nixify";
    collectedLocks = {
      url = "path:../001_collect_locks";
    };
  };

  outputs = { self, nixpkgs, flake-utils, collectedLocks, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        lib = pkgs.lib;

        # Get all individual lock file packages from 001_collect_locks
        allLockFilePackages = collectedLocks.outputs.${system}.packages;

        # Process each individual lock file package
        processedLockFilePackages = lib.mapAttrs
          (
            name: lockFilePackage:
              pkgs.runCommand "processed-${name}"
                {
                  inherit lockFilePackage;
                  nativeBuildInputs = [ pkgs.jq ];
                }
                ''
                  mkdir -p $out
                  # Read the lock file info and add some processing/metadata
                  jq '. + { processedAt: "$(date -uIs)" }' $lockFilePackage/lock-file-info.json > $out/processed-lock-file-info.json
                ''
          )
          allLockFilePackages;

        # Create a meta-package that collects all processed lock file infos into a single JSON array
        allProcessedLocksMetaPackage = pkgs.runCommand "all-processed-locks-data"
          {
            nativeBuildInputs = [ pkgs.jq ];
            processedInputs = builtins.toJSON (builtins.attrValues processedLockFilePackages);
          }
          ''
            mkdir -p $out
            # Use a while loop to avoid ARG_MAX issues with a large number of inputs
            echo "$processedInputs" | jq -r '.[]' | while read -r input_path; do
              cat "$input_path/processed-lock-file-info.json"
            done | jq -s . > $out/all-processed-locks.json
          '';

      in
      {
        packages = processedLockFilePackages // {
          default = allProcessedLocksMetaPackage;
        };

        checks.allProcessedPackageNames = pkgs.runCommand "all-processed-package-names"
          {
            nativeBuildInputs = [ pkgs.jq ];
            processedPackageNames = builtins.toJSON (builtins.attrNames processedLockFilePackages);
          }
          ''
            mkdir -p $out
            echo "$processedPackageNames" > $out/names.json
          '';
        docs.usage = pkgs.writeText "usage.md" ''
          # Flake: 002c_collected_locks_derivation

          ## Purpose

          This flake consumes the individual lock file packages generated by `001_collect_locks` and processes each of them. It then provides access to these individually processed packages and a meta-package that aggregates all processed data into a single JSON array.

          ## Inputs

          *   `nixpkgs`: Standard Nixpkgs input.
          *   `flake-utils`: Utility functions for Nix flakes.
          *   `collectedLocks`: The output of the `001_collect_locks` flake, providing individual lock file packages.

          ## Outputs

          *   `packages.*`: Individual derivations, each containing a `processed-lock-file-info.json` for a specific processed `flake.lock` file. The attribute names correspond to the input `lock-file-0`, `lock-file-1`, etc.
          *   `packages.default`: A meta-derivation containing `all-processed-locks.json`, which is a JSON array of all `processed-lock-file-info.json` contents from the individual packages.
          *   `checks.allProcessedPackageNames`: A check that outputs a JSON array of the attribute names of the `packages.*` derivations (e.g., `["processed-lock-file-0", "processed-lock-file-1"]`), useful for debugging and verification.

          ## Usage

          To build a specific processed lock file package (e.g., the first one):

          ```bash
          nix build .#packages.processed-lock-file-0
          cat ./result/processed-lock-file-info.json
          ```

          To build the meta-package containing all processed lock file data:

          ```bash
          nix build .#default
          cat ./result/all-processed-locks.json
          ```

          To inspect the names of all processed lock file packages:

          ```bash
          nix build .#checks.allProcessedPackageNames
          cat ./result/names.json
          ```

          This flake is designed to be chained with subsequent flakes in the audit process.
        '';
      }
    );
}
